"""add document processing status

Revision ID: 37221d08a476
Revises: 67c74f599d65
Create Date: 2026-09-09 13:44:27.683071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37221d08a476'
down_revision: Union[str, Sequence[str], None] = '67c74f599d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.Text(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
